### ISSUE TITLE
Live Demo Died （網頁版找不到 DNS）

### ISSUE THREAD

**Issue by gc-octopis** [dsh0416/fast-srt-subtitle#5]
剛剛想透過 <https://srt.coderemixer.com> 上字幕的時候，發現網站連不進去。

希望原作能盡快修復，謝謝。

---

### EDIT: 在修好之前你可以到 [waybackmachine](https://web.archive.org/web/20230126065010/https://srt.coderemixer.com/) 上面使用以前的備份。

**Comment by dsh0416** [comment]
非常感謝您的報告，確實是在 DNS 設定上有一處錯誤，目前已經修復。

Thank you for your report, there was misconfiguration in DNS settings, the problem has been resolved.
